- README.md
> update read me again

- Backend/models/candidate.js
This code is for managing a Candidate entity in a voting system.
> Created mongoDB schema for candidate.

- Backend/models/complaint.js
In this defines Mongoose schema for a MongoDB collection named as "complaint". It structures the data for handling user complaints.
> Place the mongodb schema for complaints file inside the models folder

- Backend/Services/GenericService.js
Implemented Common code for doing some common operations like getAll, getById,deleteById,getCount. I implemented this code why because we can reuse those functions.
> Implemented Generic Service code

- Backend/routers/complaints.js
This defines routes for handling complaints in our application. It includes,
1.Fetching all complaints with associated user and candidate details.
2.Fetching complaints by a specific user ID.
3.Retrieving a single complaint by its ID.
4.Proper error handling for robust API responses.
> Add complaints route,fetch all,by user ID,and by complaint by

- Backend/routers/complaints.js
Update routes for managing complaints, including creation, deletion, fetching pending review and updating review status.
> Modify complaints route with CRUD functionality

- Frontend/my-app/src/Components/About/About.css
- Frontend/my-app/src/Components/About/About.jsx
Includes detailed features, FAQs, and styling for an engaging user experience.
> Add React 'About' component for ElectS

- Admin/package-lock.json
- Admin/package.json
- Admin/src/App.jsx
- Admin/src/components/Login.jsx
This pull request introduces a basic functional Admin Login component. Key features include:
Input fields for username and password.
Basic validation to ensure both fields are required.
Displays an error message for missing fields or invalid credentials.
Simulated login functionality, where a successful login is achieved with username: "admin" and password: "admin123".
This component is styled minimally with inline styles and is ready for integration into the main application. Future enhancements can include:
Improved styling.
Integration with backend authentication APIs.
Enhanced validation logic.
Please review and suggest any improvements.
> Add Basic Admin Login Component

- Frontend/my-app/src/Components/Navbar/Navbar.css
add some styles for header and navbar
> add some styles for navbar

- Frontend/my-app/src/Components/Welcome/Welcome.jsx
This Welcome component creates a landing page for "ElectS," showcasing the app name, tagline, a brief description, navigation links, and styled images to enhance the visual appeal.
> Created Welcome page

- Backend/routers/candidates.js
Added a feature to update candidate and user details, including support for uploading profile photos and updating passwords. Introduced a voting feature that lets users vote for candidates while ensuring they can't vote more than once in the same election. Improved ID validation and error handling to make the system more reliable.
> Add candidate update and voting endpoints.

- Frontend/my-app/src/Components/Footer/Footer.css
footer file updated. let me know if there have some changes.
> Footer.css file created and updated

- Backend/models/party.js
- Added fields for name, abbreviation, logo, leader, founding date, and headquarters.
- Established relationships with Candidate and Election models.
- Included contact details, website, and tracking for elections participated.
- Added middleware for automatic `updatedAt` updates.
> Implemented Political Party model with comprehensive schema

- Frontend/my-app/src/Components/Navbar/Navbar.css
Add responsive navbar and header styling with animations and tooltips.
> add some css to Navbar

- Frontend/my-app/src/Components/Navbar/Navbar.css
Updated navbar styles for improved design.
> updated navbar styles

- Frontend/my-app/src/Pages/Dashboard.jsx
adding authentication handling, routing and  unauthorized access.
> Add authentication handling and routing in Dashboard

- Backend/routers/parties.js
- Implement route to fetch all political parties
- Add route to fetch all party names
- Implement route to fetch party details by ID, including populated data 
- Handle errors and provide appropriate status codes
> Add API routes for political parties management

- Backend/routers/candidates.js
Added functionality to manage candidate verifications. One endpoint fetches a list of candidates awaiting approval, including their user and party details. Another endpoint allows candidates to be approved or rejected by updating their verification status.
> Add routes for managing candidate verifications

- Frontend/my-app/src/Components/Election/Election.jsx
Added state management and API call to fetch elections.
> Add Initial State Management and Election Fetching

- Frontend/my-app/src/Pages/CSS/Dashboard.css
- Frontend/my-app/src/Pages/Dashboard.jsx
Dashboard.css is done and make some changes in Dashboard.jsx file as well
> CSS parts done in dashboard

- Frontend/my-app/src/Components/Election/Election.jsx
Render Election List and Apply Button and fixed some errors and
> Render Election List and Apply Button

- Backend/routers/parties.js
- Implement POST route to create a new political party with support for file upload (logo).
- Implement PUT route to update an existing political party, allowing partial updates and file upload for logo.
- Add error handling for missing fields and server errors.
>  Update routes for creating and updating political parties

- Backend/routers/Elections.js
Add missing module.exports = router to export the router module
> fix the error

- Backend/routers/candidates.js
Created a GET endpoint at '/candidates' to fetch all candidates from the database.
Used Mongoose's `populate` method to include the 'name' field from the mentioned 'user' collection.
> Add endpoint to fetch all candidates with populate

- Backend/index.js
Join candidate routes into the application.
> Add candidates to index.js

- Backend/routers/candidates.js
Check if the ID is a valid MongoDB ObjectId.
Fetch candidate by ID and populate user details.
> Updated get candidates by id

- Backend/models/candidate.js
To connect the candidate with a political party from the PoliticalParty collection.
> Add party attribute to Candidate model.

- Backend/helpers/uploadfile.js
added some functions to upload file like file storage configuration, file type filtering and  file size limits
> upload file created and updated

- Frontend/my-app/package-lock.json
- Frontend/my-app/package.json
- Frontend/my-app/src/App.js
- Frontend/my-app/src/Components/Contact/Contact.jsx
- Frontend/package-lock.json
-Implemented a Contact form with name, email, and message fields.
- Integrated EmailJS to handle email sending via the `sendEmail` function.
- Included success and failure alerts for user feedback.
- Added a reusable Navbar component to the Contact page.
> Add Contact component with email functionality using EmailJS

- Frontend/my-app/src/Components/Complaint/Complaint.jsx
Complaint and complaintForm  folders created in components in frontend.
> Complaint and complaintForm component folders created 

- Frontend/my-app/src/Components/Contact/Contact.css
- Frontend/my-app/src/Components/Contact/Contact.jsx
-Created a contact form component.
- Integrated EmailJS for sending email functionality.
- Added form validation and success/failure notifications.
> Add contact form functionality with EmailJS integration

- Frontend/my-app/src/Components/Contact/Contact.jsx
Added form.current.reset() to reset the form fields after sending the email successfully.
> Clear form fields after successful email submission

- Frontend/my-app/src/Components/AddProjectCandidate/AddProjectCandidate.jsx
Sends a GET request to check if the user is a candidate.
Displays an error message using SweetAlert if the status check fails.
> Add function to verify user candidate status in AddProjectCandidate.

- Frontend/my-app/src/Components/Complaint/Complaint.css
Complaint.css updated check for any changes
> Complaint.css updated

- Frontend/my-app/src/Components/ComplaintForm/ComplaintForm.css
- Frontend/my-app/src/Components/ComplaintForm/ComplaintForm.jsx
complaintForm updated.  check this out.
> complaaintForm.jxs updated

- Frontend/my-app/src/Components/ComplaintForm/ComplaintForm.css
> Complaint css updated

- Admin/src/components/Register/Register.jsx
Add Admin id to the registration form
> fix:Add Admin id

- Frontend/my-app/src/Components/AddProjectCandidate/AddProjectCandidate.jsx
Created a simple form structure with sections for title, description, links, and attachments and submit button for future submission handling.
> feat:Add basic structure for the project submission form.

- Frontend/my-app/src/Components/AddProjectCandidate/AddProjectCandidate.css
Styled the project submission form with a clean, modern design using flexbox for layout.
> style:Add styling for project submission form.

- Frontend/my-app/src/Components/AddProjectCandidate/AddProjectCandidate.jsx
Implemented controlled components for the project title, description, and links input fields.
> feat:Add usestate for project submission form inputs.

- Admin/src/components/ComplaintReview/ComplaintReview.css
- Admin/src/components/ComplaintReview/ComplaintReview.jsx
Fetch Pending Complaints:
This pull request introduces the ComplaintReview component for managing complaint reviews in the system.
> Integrate  

- Frontend/my-app/src/Components/AddProjectCandidate/AddProjectCandidate.jsx
Added handleAttachmentChange function to update the attachments state when files are selected.
> feat:Add file upload handling for project attachments.

- Frontend/my-app/src/Components/AddProjectCandidate/AddProjectCandidate.jsx
Add the handleSubmit function with the e.preventDefault() method to prevent default form behavior.
> feat:Add basic handleSubmit function skeleton.

- Frontend/my-app/src/Components/AddProjectCandidate/AddProjectCandidate.jsx
Add the FormData setup for capturing form inputs and files.
> feat:Set up FormData for capturing project details and attachments.

- Admin/src/components/AddElection/AddElection.jsx
Create the basic component structure, import libraries, and initialize the state with useState.
> feat:Set up AddElection component structure.

- Admin/src/components/AddElection/AddElection.jsx
Add form fields for name, location, date, description, and rules
> feat:Add Form Elements.

- Admin/src/components/AddElection/AddElection.jsx
Use react-datepicker for selecting Start Time and End Time.
> feat:Added time period selection functionality.

- Admin/src/components/AddElection/AddElection.jsx
Implement countdown logic with useEffect to show election countdown and status dynamically.
> feat:Add countdown timer logic to display time left until election.

- Admin/src/components/AddElection/AddElection.jsx
Add the handleSubmit method to combine the selected date, start time, and end time and send the election data to the backend.
> feat:Add form submission logic with API integration and feedback.

- Admin/src/components/AddElection/AddElection.css
- Admin/src/components/AddElection/AddElection.jsx
Add style including inputs, time picker, buttons, and overall layout.
> feat:Add style to the AddElection

- Frontend/my-app/src/Components/Results/Results.css
-Adds a comprehensive CSS file to style the results page, charts, and candidate cards.
-Key sections styled include the results container, form, charts, and candidate cards.
> Add styling for results page, charts, and candidate cards

- Admin/package-lock.json
- Admin/src/components/PartyList/PartyList.jsx
- Admin/src/components/ProjectReview/ProjectReview.css
- Admin/src/components/ProjectReview/ProjectReview.jsx
> project review and party list  updated

- Backend/routers/candidates.js
Updated the candidates endpoint to fetch candidates with populated user details.
> refactor:Refactored the candidates endpoint.

- Frontend/my-app/package-lock.json
- Frontend/my-app/package.json
- Frontend/my-app/src/Components/Footer/Footer.jsx
let me know there have some changes
> footer updated

- Backend/routers/candidates.js
Added a check to validate if the userId is a valid MongoDB ObjectId.
> feat:Added User ID validation for /user/count/:userId endpoint.

- Backend/routers/candidates.js
Sends a 200 status code with the project count.
> feat:Added success response for /user/count/:userId endpoint.

- Backend/routers/candidates.js
Added a try-catch block to handle errors during database operations.
Sends a 500 status code with a message if an internal error occurs.
> feat:Added error handling for /user/count/:userId endpoint.

- Backend/routers/candidates.js
Modified the User update logic to handle separate firstName and lastName fields instead of a single name field.
> feat:Update candidate details API to include first and last name fields.

- Admin/src/components/ElectionSideBar/ElectionSideBar.css
- Admin/src/components/ElectionSideBar/ElectionSideBar.jsx
- Admin/src/components/Home/Home.css
- Admin/src/components/Home/Home.jsx
- Admin/src/components/PartyList/PartyList.css
- Admin/src/components/PartyList/PartyList.jsx
- Admin/src/components/ProjectReview/ProjectReview.jsx
check all the admin parts i have done
> Admin parts checked

- Backend/helpers/uploadfile.js
- Frontend/my-app/src/Components/ComplaintForm/ComplaintForm.css
- Frontend/my-app/src/Components/ComplaintForm/ComplaintForm.jsx
- Frontend/my-app/src/Pages/CSS/Dashboard.css
- Frontend/my-app/src/Pages/Dashboard.jsx
check all the parts of frontend
> frontend checked done

- Admin/src/components/Elections/ParlimentElection/ParlimentElection.jsx
Initialize the ParlimentElection component with React, Axios for API requests, and import CSS for styling.
> feat:Import necessary libraries and CSS

- Admin/src/components/Elections/ParlimentElection/ParlimentElection.jsx
Set up state variables to manage election form inputs, including year, date, timings, description, rules, and error handling.
> feat:Define state variables for form data.

- Frontend/my-app/src/Components/Complaint/Complaint.css
- Frontend/my-app/src/Components/Complaint/Complaint.jsx
frontend/components/complaint updated
> complaint updated

- Admin/src/App.jsx
This pull request ensures that certain routes in the application are protected and only accessible to authenticated users. The following changes have been made:
Protected Routes:
Wrapped the Projects, Complaints, ElectionSideBar, ElectionList, UpdateElection, [Party](vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html), [PartyList](vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html), [UpdateParty](vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html), and …
> Protect Routes with Authentication

- Admin/src/components/Elections/ParlimentElection/ParlimentElection.jsx
Add a handleFormSubmit function to send election details to the backend, handle success cases, and reset form inputs and export the ParlimentElection component.
> feat:Create a form submission handler.

- Admin/src/components/Users/Users.css
- Admin/src/components/Users/Users.jsx
Changes:
- Added state variables for selected province and district.
- Added filtering logic based on selected province and district.
- Updated the Users component to include dropdowns for selecting province and district.
How to Test:
1. Navigate to the Users page.
2. Use the dropdowns to filter users by province and district.
3. Verify that the user list updates based on the selected filters.
Related Issues:
(Optional) Link to any related issues or tickets.
> This pull request adds filtering functionality for users by province and district in the Users component.

- Frontend/my-app/src/Components/ElectionDetailsParlimentary/ElectionDetailsParlimentary.jsx
Added initial structure for the ElectionDetailsParlimentary component, including state management, routing setup, and basic placeholders for election details and candidates.
> feat: initialize ElectionDetailsParlimentary component structure.

- Frontend/my-app/src/Components/ElectionDetailsParlimentary/ElectionDetailsParlimentary.jsx
Implemented API calls to retrieve election details and candidate information using Axios.
> feat: add API calls to fetch election and candidate data.

- Frontend/my-app/src/Components/ElectionDetailsParlimentary/ElectionDetailsParlimentary.jsx
Added a countdown timer to display the time remaining until the election starts or ends dynamically.
> feat: implement countdown timer for election start and end.

- Frontend/my-app/src/Components/ElectionDetailsParlimentary/ElectionDetailsParlimentary.jsx
Implemented rendering of election details along with appropriate loading and error state management.
> feat: render election details and handle loading/error states.

- Frontend/my-app/src/Components/ElectionDetailsParlimentary/ElectionDetailsParlimentary.jsx
Added functionality to display the list of candidates and implemented voting logic with validations for election status and user actions.
> feat: render candidates list and handle voting logic.

- Frontend/my-app/src/Components/ElectionDetailsParlimentary/ElectionDetailsParlimentary.jsx
Implemented a function to navigate to the candidate details page when a candidate's row is clicked in the candidates list.
> feat: add navigation to candidate details on row click.

- Backend/models/reportFake.js
backend/models/reportFake    updated
check for issues
> reportFake updated in backend models

- Frontend/my-app/src/Components/ComplaintList/ComplaintList.jsx
Enhanced the ComplaintList component to dynamically display detailed complaint information, including:
Complaint title, description, and creation date.
A list of attached proofs with clickable links to view them.
A navigation link to report the complaint as fake, directing users to a dedicated reporting page.
> feat: render complaint details with proofs and reporting links.

- Frontend/my-app/src/Components/ComplaintList/ComplaintList.css
Styled the ComplaintList component, including the container, title, list items, proof links, and hover effects.
> style:Add style to the complaintlist

- Frontend/my-app/src/Components/ReportFake/ReportFake.jsx
Added the ReportFake component with a structured layout, including form fields for explanation and file uploads. Integrated state management using useState and captured the complaint ID using useParams().
> feat: initialize ReportFake component structure

- Frontend/my-app/src/Components/ReportFake/ReportFake.jsx
Added an API call using axios.post to submit fake complaint reports. Form data is structured with complaint ID, explanation, and attached proof files. Handles success and error responses with appropriate user feedback.
> feat: implement API call to submit fake complaint report

- Frontend/my-app/src/Components/ReportFake/ReportFake.css
Implemented CSS styles for the ReportFake component.
> style:Added style to reportfake.js
